# Generated by Django 3.2.13 on 2022-04-23 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('birthday', models.DateField()),
                ('position', models.CharField(max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_direction', models.CharField(max_length=120)),
                ('date', models.DateField(default=datetime.date(2022, 4, 23))),
                ('addressee', models.ManyToManyField(to='docs.Employee')),
            ],
            options={
                'verbose_name': ('Документ',),
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
