# Generated by Django 3.2.13 on 2022-04-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type_doc',
            field=models.CharField(choices=[('WD', 'Справка с места работы'), ('DM', 'Увольнение')], default='WD', max_length=2),
        ),
    ]
